spring.application.name=cloudcompare-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cloudcompare
spring.datasource.username=cloudcompare
spring.datasource.password=838W4+w>0tui_o7lSLJUbE8D{.))B>[:
spring.datasource.driver-class-name=org.postgresql.Driver

logging.file.name=/app/logs/cloudcompare-backend.log
logging.level.root=INFO
logging.level.org.cloudcompare=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.servlet.context-path=/api

openai.api.key=${OPENAI_API_KEY}
gcp.api.key=${GCP_API_KEY}
jwt.secret=${JWT_SECRET}